# Generated by Django 2.2 on 2020-10-31 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('initiative', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='character',
            name='campaign_joined',
        ),
        migrations.AddField(
            model_name='character',
            name='campaigns_joined',
            field=models.ManyToManyField(related_name='characters', to='initiative.Campaign'),
        ),
    ]
