# Generated by Django 2.2 on 2020-11-07 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('initiative', '0002_auto_20201031_0110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='code',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
